[project]
version = "0.1.0"
name = "zargv"
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
err = "*"
list = "*"
log = "*"
pool = "*"

[repos]
list = "git://github.com/jwerle/zz-list.git"
